"""Regenerate ``wiki/index.md`` from the on-disk wiki tree.

The index is a *content-oriented catalogue* (Karpathy's framing): every K-page
appears grouped by its folder, with a one-line summary that's either the
first non-heading paragraph or a truncated body snippet. Deterministic output
so the file diffs cleanly between runs.
"""

from __future__ import annotations

import re
from pathlib import Path

import frontmatter

INDEX_PATH = "wiki/index.md"

_HEADING = re.compile(r"^\s{0,3}#{1,6}\s")
_INDEX_HEADER = (
    "---\n"
    "type: index\n"
    "updated: {updated}\n"
    "---\n\n"
    "# Wiki Index\n\n"
    "> Auto-generated by `dikw synth`. Do not edit by hand — changes will be overwritten.\n"
)


def _first_paragraph(body: str) -> str:
    lines: list[str] = []
    for raw in body.splitlines():
        stripped = raw.strip()
        if not stripped:
            if lines:
                break
            continue
        if _HEADING.match(raw):
            # skip headings; we want the first body paragraph
            continue
        lines.append(stripped)
    text = " ".join(lines)
    return (text[:200] + "…") if len(text) > 200 else text


def _page_entries(wiki_dir: Path) -> list[tuple[str, str, str, str]]:
    """Return (folder, title, rel_path, summary) tuples for every wiki page."""
    entries: list[tuple[str, str, str, str]] = []
    for md in sorted(wiki_dir.rglob("*.md")):
        if md.name == "index.md" or md.name == "log.md":
            continue
        rel = md.relative_to(wiki_dir.parent)  # wiki/...
        try:
            post = frontmatter.load(str(md))
        except Exception:
            continue
        if not post.content.strip():
            continue
        folder = md.parent.name  # e.g. "concepts"
        meta = post.metadata
        title = str(meta.get("title") or md.stem.replace("-", " ").title())
        summary = _first_paragraph(post.content) or "(empty page)"
        entries.append((folder, title, str(rel).replace("\\", "/"), summary))
    entries.sort(key=lambda e: (e[0], e[1].lower()))
    return entries


def regenerate_index(root: Path, *, updated: str) -> Path:
    """Rewrite ``wiki/index.md`` and return its absolute path."""
    wiki_dir = root / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)
    abs_index = root / INDEX_PATH

    entries = _page_entries(wiki_dir)

    parts: list[str] = [_INDEX_HEADER.format(updated=updated)]
    if not entries:
        parts.append("\n_No wiki pages yet — run `dikw synth` to generate some._\n")
    else:
        current_folder: str | None = None
        for folder, title, rel_path, summary in entries:
            if folder != current_folder:
                current_folder = folder
                parts.append(f"\n## {folder}\n\n")
            parts.append(f"- [[{title}]] — {summary}  \n  `{rel_path}`\n")

    abs_index.write_text("".join(parts), encoding="utf-8")
    return abs_index
