"""On-disk representation of the W layer.

Two kinds of files live on disk:

* ``wisdom/_candidates/<kind>-<slug>.md`` — one file per pending candidate.
  Humans (or Obsidian) can read these before approving.
* ``wisdom/principles.md`` / ``wisdom/lessons.md`` / ``wisdom/patterns.md`` —
  one aggregate file per kind, regenerated from the DB's approved rows.
  Think of them as the K-layer ``index.md`` analogue for the W layer.

The DB row is authoritative. Files are derived views, so ``io.py`` can
freely rewrite them.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import UTC, datetime
from pathlib import Path

from ...schemas import WisdomEvidence, WisdomItem, WisdomKind
from ..knowledge.wiki import now_iso
from .distill import WisdomCandidate, candidate_path


def _format_evidence_yaml(evidence: Sequence[WisdomEvidence]) -> str:
    """Render evidence as a YAML list suitable for a front-matter block."""
    lines: list[str] = []
    for ev in evidence:
        lines.append(f"  - doc: {ev.doc_id}")
        if ev.line is not None:
            lines.append(f"    line: {ev.line}")
        # escape double-quotes in the excerpt
        excerpt = ev.excerpt.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    excerpt: "{excerpt}"')
    return "\n".join(lines)


def write_candidate_file(
    root: Path, candidate: WisdomCandidate, *, created_iso: str | None = None
) -> Path:
    """Persist ``candidate`` to ``wisdom/_candidates/`` and return the absolute path."""
    rel = candidate_path(candidate.kind, candidate.title)
    abs_path = (root / rel).resolve()
    abs_path.parent.mkdir(parents=True, exist_ok=True)

    created = created_iso or now_iso()
    evidence_block = _format_evidence_yaml(candidate.evidence)

    lines = [
        "---",
        f"id: {candidate.item_id}",
        f"kind: {candidate.kind.value}",
        "status: candidate",
        f"title: {candidate.title}",
        f"confidence: {candidate.confidence}",
        f"created: {created}",
        "evidence:",
        evidence_block,
        "---",
        "",
        candidate.body.rstrip(),
        "",
    ]
    abs_path.write_text("\n".join(lines), encoding="utf-8")
    return abs_path


def delete_candidate_file(root: Path, kind: WisdomKind, title: str) -> bool:
    """Remove the candidate file for (kind, title) if present. Returns True iff deleted."""
    rel = candidate_path(kind, title)
    abs_path = (root / rel)
    if abs_path.is_file():
        abs_path.unlink()
        return True
    return False


_AGGREGATE_FILES: dict[WisdomKind, str] = {
    WisdomKind.PRINCIPLE: "wisdom/principles.md",
    WisdomKind.LESSON: "wisdom/lessons.md",
    WisdomKind.PATTERN: "wisdom/patterns.md",
}


def aggregate_path(kind: WisdomKind) -> str:
    return _AGGREGATE_FILES[kind]


def _format_entry(item: WisdomItem, evidence: Sequence[WisdomEvidence]) -> str:
    approved = (
        datetime.fromtimestamp(item.approved_ts, tz=UTC).strftime("%Y-%m-%d")
        if item.approved_ts is not None
        else "—"
    )
    lines = [
        f"## {item.title}",
        "",
        f"*id: `{item.item_id}` · confidence: {item.confidence:.2f} · approved: {approved}*",
        "",
        item.body.strip(),
        "",
        "**Evidence:**",
        "",
    ]
    if evidence:
        for ev in evidence:
            loc = f" (line {ev.line})" if ev.line is not None else ""
            quote = ev.excerpt.replace("\n", " ").strip()
            lines.append(f"- `{ev.doc_id}`{loc}: \"{quote}\"")
    else:
        lines.append("- _(no evidence recorded)_")
    lines.append("")
    return "\n".join(lines)


def regenerate_aggregate(
    root: Path,
    *,
    kind: WisdomKind,
    items: Sequence[WisdomItem],
    evidence_by_item: dict[str, list[WisdomEvidence]],
    updated: str | None = None,
) -> Path:
    """Rewrite the aggregate file for ``kind`` from approved items in the DB."""
    rel = aggregate_path(kind)
    abs_path = (root / rel)
    abs_path.parent.mkdir(parents=True, exist_ok=True)

    header_title = {
        WisdomKind.PRINCIPLE: "Principles",
        WisdomKind.LESSON: "Lessons",
        WisdomKind.PATTERN: "Patterns",
    }[kind]

    parts: list[str] = [
        "---",
        "type: wisdom-group",
        f"kind: {kind.value}",
        f"updated: {updated or now_iso()}",
        "---",
        "",
        f"# {header_title}",
        "",
        f"> Approved {kind.value}s distilled from the wiki. Regenerated by `dikw review`.",
        "",
    ]

    ordered = sorted(items, key=lambda x: (x.approved_ts or 0, x.title), reverse=True)
    if not ordered:
        parts.append(f"_No approved {kind.value}s yet._\n")
    else:
        for item in ordered:
            parts.append("---")
            parts.append("")
            parts.append(_format_entry(item, evidence_by_item.get(item.item_id, [])))

    abs_path.write_text("\n".join(parts), encoding="utf-8")
    return abs_path
