"""High-level engine facade used by both the CLI and the MCP server.

Phase 0 surface: ``init_wiki`` (scaffold a new wiki directory) and ``status``
(show backend counts). Subsequent phases add ``ingest``, ``synthesize``,
``distill``, ``review``, ``query``, ``lint``.
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

from .config import (
    CONFIG_FILENAME,
    DikwConfig,
    default_config,
    dump_config_yaml,
    find_config,
    load_config,
)
from .schemas import StorageCounts

if TYPE_CHECKING:
    from .storage.base import Storage


WIKI_INIT_FILES: dict[str, str] = {
    "sources/.gitkeep": "",
    "wiki/index.md": (
        "---\n"
        "type: index\n"
        "updated: auto\n"
        "---\n\n"
        "# Wiki Index\n\n"
        "This file is regenerated by `dikw synth` and `dikw lint`.\n"
        "It lists every wiki page with a one-line summary, grouped by category.\n"
    ),
    "wiki/log.md": (
        "# Wiki Log\n\n"
        "Append-only chronological record of engine activity.\n"
    ),
    "wiki/entities/.gitkeep": "",
    "wiki/concepts/.gitkeep": "",
    "wiki/notes/.gitkeep": "",
    "wisdom/principles.md": (
        "---\n"
        "type: wisdom-group\n"
        "kind: principle\n"
        "---\n\n"
        "# Principles\n\n"
        "Approved principles will be appended here. See `wisdom/_candidates/`\n"
        "for candidates awaiting human review.\n"
    ),
    "wisdom/lessons.md": (
        "---\n"
        "type: wisdom-group\n"
        "kind: lesson\n"
        "---\n\n"
        "# Lessons\n"
    ),
    "wisdom/patterns.md": (
        "---\n"
        "type: wisdom-group\n"
        "kind: pattern\n"
        "---\n\n"
        "# Patterns\n"
    ),
    "wisdom/_candidates/.gitkeep": "",
    ".dikw/.gitkeep": "",
    ".gitignore": ".dikw/\n",
}


def init_wiki(root: str | Path, *, description: str | None = None) -> Path:
    """Scaffold a new dikw wiki at ``root``.

    Creates the directory layout and a ``dikw.yml`` populated with defaults.
    Fails if a config already exists at the target path.
    """
    wiki_root = Path(root).resolve()
    wiki_root.mkdir(parents=True, exist_ok=True)

    existing = wiki_root / CONFIG_FILENAME
    if existing.exists():
        raise FileExistsError(f"{existing} already exists; refusing to overwrite")

    cfg = default_config(description=description or f"dikw wiki at {wiki_root.name}")
    existing.write_text(dump_config_yaml(cfg), encoding="utf-8")

    for rel_path, body in WIKI_INIT_FILES.items():
        target = wiki_root / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists():
            target.write_text(body, encoding="utf-8")

    return wiki_root


def resolve_wiki_root(path: str | Path | None) -> Path:
    """Return the nearest wiki root (dir containing ``dikw.yml``) walking up from ``path``."""
    start = Path(path) if path is not None else Path.cwd()
    found = find_config(start)
    if found is None:
        raise FileNotFoundError(
            f"no {CONFIG_FILENAME} found at or above {start.resolve()}"
        )
    return found.parent


def load_wiki(path: str | Path | None = None) -> tuple[DikwConfig, Path]:
    root = resolve_wiki_root(path)
    return load_config(root / CONFIG_FILENAME), root


async def _with_storage(path: str | Path | None) -> tuple[DikwConfig, Path, Storage]:
    """Open and migrate the Storage backend for the wiki rooted near ``path``."""
    from .storage import build_storage  # local import to avoid cycle at module import

    cfg, root = load_wiki(path)
    storage = build_storage(cfg.storage, root=root)
    await storage.connect()
    await storage.migrate()
    return cfg, root, storage


async def status(path: str | Path | None = None) -> StorageCounts:
    """Return storage counts across all DIKW layers for the nearest wiki."""
    _cfg, _root, storage = await _with_storage(path)
    try:
        return await storage.counts()
    finally:
        await storage.close()
