"""High-level engine facade used by both the CLI and the MCP server.

Phase 1 surface:
  * ``ingest`` — walk configured sources, parse markdown, chunk, embed, index.
  * ``query`` — hybrid search + LLM answer with citations.

Phase 2 surface:
  * ``synthesize`` — turn source docs into K-layer wiki pages via the LLM,
    persist them to disk + storage, maintain the link graph, and refresh
    ``wiki/index.md`` + ``wiki/log.md``.
  * ``lint`` — report broken wikilinks, orphans, and duplicate titles.

Phase 3 surface:
  * ``distill`` — propose W-layer wisdom items from K-layer pages.
  * ``list_candidates`` / ``approve_wisdom`` / ``reject_wisdom`` —
    drive the review state machine.
  * ``query`` — unchanged call signature, but now surfaces applicable
    approved wisdom items alongside excerpts.

Phase 0 surface (``init_wiki``, ``status``) stays unchanged.
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel

from . import prompts
from .config import (
    CONFIG_FILENAME,
    DikwConfig,
    default_config,
    dump_config_yaml,
    find_config,
    load_config,
)
from .data.assets import materialize_asset
from .data.backends import UnsupportedFormat, parse_any
from .data.backends.base import ParsedDocument
from .data.backends.markdown import content_hash
from .data.sources import iter_source_files
from .info.chunk import chunk_markdown
from .info.embed import (
    ChunkToEmbed,
    embed_assets,
    embed_chunks,
    embed_chunks_multimodal,
)
from .info.search import Hit, HybridSearcher, MultimodalSearch
from .knowledge.indexgen import regenerate_index
from .knowledge.links import parse_links, resolve_links
from .knowledge.lint import LintReport, run_lint
from .knowledge.log import render_log
from .knowledge.synthesize import SynthesisError, parse_synthesis_response
from .knowledge.wiki import WikiPage, now_iso, write_page
from .providers import (
    EmbeddingProvider,
    LLMProvider,
    MultimodalEmbeddingProvider,
    build_embedder,
    build_llm,
    build_multimodal_embedder,
)
from .schemas import (
    AssetRecord,
    ChunkAssetRef,
    ChunkRecord,
    DocumentRecord,
    EmbeddingVersion,
    Layer,
    StorageCounts,
    WikiLogEntry,
    WisdomEvidence,
    WisdomItem,
    WisdomStatus,
)
from .storage import Storage, build_storage
from .storage.base import NotSupported, StorageError
from .wisdom.apply import ApplicableWisdom, pick_applicable
from .wisdom.distill import WisdomCandidate, parse_distill_response
from .wisdom.io import write_candidate_file
from .wisdom.review import (
    ReviewError,
    ReviewResult,
)
from .wisdom.review import approve as _approve_item
from .wisdom.review import reject as _reject_item

logger = logging.getLogger(__name__)

__all__ = [
    "AppliedWisdomRef",
    "CheckReport",
    "Citation",
    "DistillReport",
    "IngestReport",
    "ProbeResult",
    "QueryResult",
    "ReviewError",
    "ReviewResult",
    "SynthReport",
    "approve_wisdom",
    "check_providers",
    "distill",
    "find_config",
    "ingest",
    "init_wiki",
    "lint",
    "list_candidates",
    "load_wiki",
    "query",
    "reject_wisdom",
    "status",
    "synthesize",
]

WIKI_INIT_FILES: dict[str, str] = {
    "sources/.gitkeep": "",
    "wiki/index.md": (
        "---\n"
        "type: index\n"
        "updated: auto\n"
        "---\n\n"
        "# Wiki Index\n\n"
        "This file is regenerated by `dikw synth` and `dikw lint`.\n"
        "It lists every wiki page with a one-line summary, grouped by category.\n"
    ),
    "wiki/log.md": (
        "# Wiki Log\n\n"
        "Append-only chronological record of engine activity.\n"
    ),
    "wiki/entities/.gitkeep": "",
    "wiki/concepts/.gitkeep": "",
    "wiki/notes/.gitkeep": "",
    "wisdom/principles.md": (
        "---\n"
        "type: wisdom-group\n"
        "kind: principle\n"
        "---\n\n"
        "# Principles\n\n"
        "Approved principles will be appended here. See `wisdom/_candidates/`\n"
        "for candidates awaiting human review.\n"
    ),
    "wisdom/lessons.md": (
        "---\n"
        "type: wisdom-group\n"
        "kind: lesson\n"
        "---\n\n"
        "# Lessons\n"
    ),
    "wisdom/patterns.md": (
        "---\n"
        "type: wisdom-group\n"
        "kind: pattern\n"
        "---\n\n"
        "# Patterns\n"
    ),
    "wisdom/_candidates/.gitkeep": "",
    ".dikw/.gitkeep": "",
    ".gitignore": ".dikw/\n",
}


# ---- public result models ------------------------------------------------


@dataclass(frozen=True)
class IngestReport:
    scanned: int = 0
    added: int = 0
    updated: int = 0
    unchanged: int = 0
    chunks: int = 0
    embedded: int = 0
    assets: int = 0  # NEW assets materialized this run
    asset_embedded: int = 0  # asset-level vectors written this run


@dataclass(frozen=True)
class SynthReport:
    candidates: int = 0
    created: int = 0
    updated: int = 0
    skipped: int = 0
    errors: int = 0


@dataclass(frozen=True)
class DistillReport:
    pages_read: int = 0
    candidates_added: int = 0
    rejected: int = 0
    errors: int = 0


class Citation(BaseModel):
    n: int
    path: str
    title: str | None = None
    layer: str
    # Chunk sequence within ``path``; populated when chunk-level retrieval
    # surfaced this citation. Disambiguates "doc X chunk 2 vs doc X chunk 5"
    # when multiple chunks from the same document end up in the citation list.
    seq: int | None = None
    excerpt: str


class AppliedWisdomRef(BaseModel):
    ref: str
    item_id: str
    kind: str
    title: str


class QueryResult(BaseModel):
    answer: str
    citations: list[Citation]
    applied_wisdom: list[AppliedWisdomRef] = []


class ProbeResult(BaseModel):
    """One leg of a ``check`` — either the LLM or the embedding endpoint."""

    ok: bool
    target: str  # the configured endpoint (or "(provider default)")
    detail: str  # on success: timing + basic stats; on failure: error message


class CheckReport(BaseModel):
    """Result of ``check_providers`` — per-leg connectivity probes.

    Either leg may be ``None`` when skipped via ``llm_only`` / ``embed_only``.
    ``ok`` is True when every *present* leg is ok (and at least one is present).
    """

    llm: ProbeResult | None = None
    embed: ProbeResult | None = None

    @property
    def ok(self) -> bool:
        legs = [p for p in (self.llm, self.embed) if p is not None]
        return bool(legs) and all(p.ok for p in legs)


# ---- wiki scaffolding (Phase 0) -----------------------------------------


def init_wiki(root: str | Path, *, description: str | None = None) -> Path:
    wiki_root = Path(root).resolve()
    wiki_root.mkdir(parents=True, exist_ok=True)

    existing = wiki_root / CONFIG_FILENAME
    if existing.exists():
        raise FileExistsError(f"{existing} already exists; refusing to overwrite")

    cfg = default_config(description=description or f"dikw wiki at {wiki_root.name}")
    existing.write_text(dump_config_yaml(cfg), encoding="utf-8")

    for rel_path, body in WIKI_INIT_FILES.items():
        target = wiki_root / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.exists():
            target.write_text(body, encoding="utf-8")

    return wiki_root


def resolve_wiki_root(path: str | Path | None) -> Path:
    start = Path(path) if path is not None else Path.cwd()
    found = find_config(start)
    if found is None:
        raise FileNotFoundError(
            f"no {CONFIG_FILENAME} found at or above {start.resolve()}"
        )
    return found.parent


def load_wiki(path: str | Path | None = None) -> tuple[DikwConfig, Path]:
    root = resolve_wiki_root(path)
    return load_config(root / CONFIG_FILENAME), root


async def _with_storage(path: str | Path | None) -> tuple[DikwConfig, Path, Storage]:
    cfg, root = load_wiki(path)
    storage = build_storage(
        cfg.storage, root=root, cjk_tokenizer=cfg.retrieval.cjk_tokenizer
    )
    await storage.connect()
    await storage.migrate()
    return cfg, root, storage


async def status(path: str | Path | None = None) -> StorageCounts:
    _cfg, _root, storage = await _with_storage(path)
    try:
        return await storage.counts()
    finally:
        await storage.close()


# ---- verifiable config tool ---------------------------------------------


async def _probe_llm(
    llm: LLMProvider, model: str, target: str
) -> ProbeResult:
    started = time.perf_counter()
    try:
        resp = await llm.complete(
            system="You are a connectivity check. Reply with just: OK",
            user="ping",
            model=model,
            max_tokens=4,
            temperature=0.0,
        )
    except Exception as e:  # provider exceptions are intentionally heterogeneous
        return ProbeResult(ok=False, target=target, detail=f"{type(e).__name__}: {e}")
    elapsed_ms = int((time.perf_counter() - started) * 1000)
    input_tok = int((resp.usage or {}).get("input_tokens", 0))
    return ProbeResult(
        ok=True,
        target=target,
        detail=f"{elapsed_ms}ms, {input_tok} input tokens",
    )


async def _probe_embed(
    embedder: EmbeddingProvider,
    model: str,
    target: str,
    *,
    provider_label: str | None = None,
) -> ProbeResult:
    started = time.perf_counter()
    try:
        vectors = await embedder.embed(["ping"], model=model)
    except Exception as e:
        return ProbeResult(ok=False, target=target, detail=f"{type(e).__name__}: {e}")
    elapsed_ms = int((time.perf_counter() - started) * 1000)
    dim = len(vectors[0]) if vectors else 0
    detail = f"{elapsed_ms}ms, dim={dim}"
    if provider_label:
        detail = f"{detail}, provider={provider_label}"
    return ProbeResult(ok=True, target=target, detail=detail)


# 1x1 transparent PNG used by ``_probe_multimodal`` so the wire round-trip
# exercises Gitee's image-decoding path with the smallest possible payload.
_PROBE_PNG_1X1 = (
    b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR"
    b"\x00\x00\x00\x01\x00\x00\x00\x01\x08\x06\x00\x00\x00\x1f\x15\xc4\x89"
    b"\x00\x00\x00\rIDATx\x9cc\xfa\xcf\x00\x00\x00\x02\x00\x01\xe5'\xde\xfc"
    b"\x00\x00\x00\x00IEND\xaeB`\x82"
)


async def _probe_multimodal(
    embedder: MultimodalEmbeddingProvider,
    model: str,
    target: str,
    *,
    provider_label: str | None = None,
) -> ProbeResult:
    """Probe a multimodal embedder with a single batched text+image request.

    Sends two per-modality inputs (one text, one tiny PNG) in **one** HTTP
    call so latency stays bounded by a single RTT — no sequential probes
    that would double end-to-end time. Validation hinges on both vectors
    coming back with a consistent dim; an empty or shape-mismatched
    response surfaces as an error rather than a silent pass.
    """
    from .schemas import ImageContent, MultimodalInput

    inputs = [
        MultimodalInput(text="ping"),
        MultimodalInput(images=[ImageContent(bytes=_PROBE_PNG_1X1, mime="image/png")]),
    ]
    started = time.perf_counter()
    try:
        vectors = await embedder.embed(inputs, model=model)
    except Exception as e:
        return ProbeResult(ok=False, target=target, detail=f"{type(e).__name__}: {e}")
    elapsed_ms = int((time.perf_counter() - started) * 1000)
    if len(vectors) != 2:
        return ProbeResult(
            ok=False,
            target=target,
            detail=(
                f"{elapsed_ms}ms, expected 2 vectors (text+image), got "
                f"{len(vectors)} — provider returned a shape-mismatched batch"
            ),
        )
    dim_text = len(vectors[0])
    dim_image = len(vectors[1])
    if dim_text != dim_image:
        return ProbeResult(
            ok=False,
            target=target,
            detail=(
                f"{elapsed_ms}ms, dim mismatch text={dim_text} image={dim_image} — "
                f"per-modality vectors must share one space"
            ),
        )
    detail = f"{elapsed_ms}ms, dim={dim_text}, modalities=text+image"
    if provider_label:
        detail = f"{detail}, provider={provider_label}"
    return ProbeResult(ok=True, target=target, detail=detail)


async def check_providers(
    path: str | Path | None = None,
    *,
    llm: LLMProvider | None = None,
    embedder: EmbeddingProvider | None = None,
    multimodal_embedder: MultimodalEmbeddingProvider | None = None,
    llm_only: bool = False,
    embed_only: bool = False,
) -> CheckReport:
    """Ping the configured LLM and embedding providers.

    ``llm``, ``embedder``, and ``multimodal_embedder`` are injectable for
    tests; production callers leave them ``None`` and the factory builds
    them from ``provider:`` / ``assets.multimodal:`` in ``dikw.yml``. Two
    legs run in parallel and each reports its own result — an LLM failure
    does not short-circuit the embedding probe.

    When ``cfg.assets.multimodal`` is configured, the embed leg routes
    through ``_probe_multimodal`` (one batched text+image request) instead
    of the text-only ``_probe_embed`` — the multimodal embedder is what
    ingest actually uses for both chunks and assets, so the check must
    follow that route to remain truthful.

    ``llm_only`` / ``embed_only`` (mutually exclusive) verify a single leg.
    The skipped leg is never built or called, so a misconfigured embedding
    side cannot fail an ``--llm-only`` run.
    """
    if llm_only and embed_only:
        raise ValueError("llm_only and embed_only are mutually exclusive")

    cfg, _root = load_wiki(path)

    llm_probe: ProbeResult | None = None
    embed_probe: ProbeResult | None = None
    llm_target = cfg.provider.llm_base_url or "(provider default)"
    embed_target = cfg.provider.embedding_base_url
    embed_label = cfg.provider.embedding_provider_label
    mm_cfg = cfg.assets.multimodal

    if not embed_only:
        llm_inst = llm if llm is not None else build_llm(cfg.provider)
    if not llm_only:
        if mm_cfg is not None:
            mm_inst = (
                multimodal_embedder
                if multimodal_embedder is not None
                else build_multimodal_embedder(
                    mm_cfg.provider, base_url=mm_cfg.base_url, batch=mm_cfg.batch
                )
            )
        else:
            embed_inst = (
                embedder if embedder is not None else build_embedder(cfg.provider)
            )

    async def _embed_leg() -> ProbeResult:
        if mm_cfg is not None:
            return await _probe_multimodal(
                mm_inst, mm_cfg.model, embed_target, provider_label=embed_label
            )
        return await _probe_embed(
            embed_inst,
            cfg.provider.embedding_model,
            embed_target,
            provider_label=embed_label,
        )

    if llm_only:
        llm_probe = await _probe_llm(llm_inst, cfg.provider.llm_model, llm_target)
    elif embed_only:
        embed_probe = await _embed_leg()
    else:
        llm_probe, embed_probe = await asyncio.gather(
            _probe_llm(llm_inst, cfg.provider.llm_model, llm_target),
            _embed_leg(),
        )
    return CheckReport(llm=llm_probe, embed=embed_probe)


# ---- Phase 1: ingest -----------------------------------------------------


def _doc_id_for(layer: Layer, logical_path: str) -> str:
    return f"{layer.value}:{logical_path}"


async def ingest(
    path: str | Path | None = None,
    *,
    embedder: EmbeddingProvider | None = None,
    multimodal_embedder: MultimodalEmbeddingProvider | None = None,
) -> IngestReport:
    """Ingest every markdown file listed in ``sources:`` into the D and I layers.

    Two provider knobs:

    * ``embedder`` — text-only ``EmbeddingProvider``; populates the legacy
      ``chunks_vec`` table for the BM25-vec hybrid path. Injectable so
      tests can pass a deterministic fake.
    * ``multimodal_embedder`` — ``MultimodalEmbeddingProvider``; when
      ``cfg.assets.multimodal`` is configured this routes both chunk-text
      and image-asset bytes through one shared vector space. Asset
      binaries referenced from markdown are materialized into
      ``<root>/<assets.dir>/`` regardless of which embedder is set —
      ``chunk_asset_refs`` always reflect the on-disk structure so
      query-time consumers can render them.
    """
    cfg, root, storage = await _with_storage(path)
    owned_mm: MultimodalEmbeddingProvider | None = None
    try:
        report = IngestReport()
        to_embed: list[ChunkToEmbed] = []
        # Newly-materialized assets (deduped by asset_id) collected across
        # the run for batch image embedding at the end.
        new_assets_by_id: dict[str, AssetRecord] = {}

        # Resolve the active multimodal version once per run so chunks and
        # assets land under the same version_id. Storage backends that
        # don't yet implement the asset / versioning APIs (filesystem,
        # postgres) raise NotSupported here — we degrade to the legacy
        # text path with a warning rather than failing the run.
        mm_version_id: int | None = None
        mm_cfg = cfg.assets.multimodal
        if mm_cfg is not None:
            try:
                mm_version_id = await storage.upsert_embed_version(
                    EmbeddingVersion(
                        provider=mm_cfg.provider,
                        model=mm_cfg.model,
                        revision=mm_cfg.revision,
                        dim=mm_cfg.dim,
                        normalize=mm_cfg.normalize,
                        distance=mm_cfg.distance,
                        modality="multimodal",
                    )
                )
            except NotSupported as e:
                logger.warning(
                    "storage backend doesn't support multimodal versioning "
                    "(%s); falling back to text-only ingest",
                    e,
                )
                mm_cfg = None  # disable mm pathway for the rest of this run

        # Auto-build the multimodal embedder from config when one wasn't
        # injected — symmetric with query()'s behavior, so the typical
        # CLI / MCP / eval call site (which only passes `embedder`) still
        # produces chunk + asset vectors in the configured mm space
        # rather than indexing chunks in legacy text space and querying
        # in mm space.
        if mm_cfg is not None and multimodal_embedder is None:
            multimodal_embedder = build_multimodal_embedder(
                mm_cfg.provider,
                base_url=mm_cfg.base_url,
                batch=mm_cfg.batch,
            )
            owned_mm = multimodal_embedder

        for abs_path, logical_path in iter_source_files(cfg.sources, root=root):
            try:
                parsed = parse_any(abs_path, rel_path=logical_path)
            except UnsupportedFormat:
                # User's glob swept up a file we can't parse; skip quietly so
                # mixed-glob directories don't explode the run.
                continue
            doc_id = _doc_id_for(Layer.SOURCE, logical_path)
            existing = await storage.get_document(doc_id)

            scanned = report.scanned + 1
            # Skip the chunk/embed pipeline only when the doc body is
            # unchanged AND the doc has no asset references — the latter
            # would otherwise leave assets stale when the binary was
            # replaced on disk or the multimodal version bumped.
            if (
                existing is not None
                and existing.hash == parsed.hash
                and not parsed.asset_refs
            ):
                report = _replace(
                    report,
                    scanned=scanned,
                    unchanged=report.unchanged + 1,
                )
                continue

            await storage.put_content(parsed.hash, parsed.body)
            await storage.upsert_document(_to_document(parsed, doc_id=doc_id))

            # Materialize image references first so asset_ids are known
            # when we wire up chunk_asset_refs after chunking. Dedupe by
            # original_path so a doc that references the same image N
            # times only reads + hashes the file once.
            #
            # Asset materialization requires a storage backend that
            # implements the asset APIs. mm_cfg above is set to None
            # when the backend raised NotSupported on upsert_embed_version,
            # so this gate also degrades gracefully on filesystem /
            # postgres until those adapters land their asset impls.
            ref_assets: dict[int, AssetRecord] = {}
            if mm_cfg is not None:
                by_original_path: dict[str, AssetRecord] = {}
                for ref_idx, ref in enumerate(parsed.asset_refs):
                    cached = by_original_path.get(ref.original_path)
                    if cached is not None:
                        ref_assets[ref_idx] = cached
                        continue
                    result = await materialize_asset(
                        ref,
                        source_md_path=abs_path,
                        project_root=root,
                        get_asset=storage.get_asset,
                        upsert_asset=storage.upsert_asset,
                        dir_=cfg.assets.dir,
                    )
                    if result is not None:
                        rec, was_new = result
                        ref_assets[ref_idx] = rec
                        by_original_path[ref.original_path] = rec
                        # Only newly-materialized binaries need an
                        # embedding pass — assets already in storage
                        # from a prior run keep their existing vector,
                        # so re-ingesting an unchanged image-heavy
                        # corpus doesn't re-bill the multimodal API.
                        if was_new:
                            new_assets_by_id.setdefault(rec.asset_id, rec)

            atomic_spans = [(r.start, r.end) for r in parsed.asset_refs]
            chunks = chunk_markdown(parsed.body, atomic_spans=atomic_spans)
            chunk_records = [
                ChunkRecord(
                    doc_id=doc_id, seq=c.seq, start=c.start, end=c.end, text=c.text
                )
                for c in chunks
            ]
            chunk_ids = await storage.replace_chunks(doc_id, chunk_records)

            # Project body-relative ref offsets into chunk-relative offsets
            # and persist the chunk ↔ asset bridge rows.
            for chunk_record, chunk_id in zip(chunk_records, chunk_ids, strict=True):
                chunk_refs: list[ChunkAssetRef] = []
                ord_counter = 0
                for ref_idx, ref in enumerate(parsed.asset_refs):
                    if not (
                        chunk_record.start <= ref.start
                        and ref.end <= chunk_record.end
                    ):
                        continue
                    asset = ref_assets.get(ref_idx)
                    if asset is None:
                        continue  # unresolved (remote URL, missing file) — already logged
                    chunk_refs.append(
                        ChunkAssetRef(
                            chunk_id=chunk_id,
                            asset_id=asset.asset_id,
                            ord=ord_counter,
                            alt=ref.alt,
                            start_in_chunk=ref.start - chunk_record.start,
                            end_in_chunk=ref.end - chunk_record.start,
                        )
                    )
                    ord_counter += 1
                if chunk_refs:
                    await storage.replace_chunk_asset_refs(chunk_id, chunk_refs)

            # Queue chunks for embedding when ANY embedder is wired up —
            # the multimodal path also needs them, even when no legacy
            # text embedder is provided.
            if (embedder is not None or multimodal_embedder is not None) and chunk_records:
                to_embed.extend(
                    ChunkToEmbed(chunk_id=cid, text=r.text)
                    for cid, r in zip(chunk_ids, chunk_records, strict=True)
                )

            await storage.append_wiki_log(
                WikiLogEntry(ts=time.time(), action="ingest", src=logical_path)
            )
            report = _replace(
                report,
                scanned=scanned,
                added=report.added if existing is not None else report.added + 1,
                updated=report.updated + 1 if existing is not None else report.updated,
                chunks=report.chunks + len(chunk_records),
            )

        # Chunk-text embeddings: prefer the multimodal pathway when both an
        # mm provider and a configured multimodal version are available.
        if to_embed:
            if multimodal_embedder is not None and mm_cfg is not None:
                rows = await embed_chunks_multimodal(
                    multimodal_embedder,
                    to_embed,
                    model=mm_cfg.model,
                    batch_size=mm_cfg.batch,
                )
                # The legacy chunks_vec table is dim-locked at first
                # write; if the user previously indexed with a different
                # text-embedding dim, writing mm vectors here would
                # raise StorageError. Asset retrieval still works (it
                # uses a per-version vec_assets_v<id> table); skip the
                # chunk-vec write with a clear warning so ingest doesn't
                # die. v1 limitation: per-version chunk vec tables land
                # in v1.5.
                try:
                    await storage.upsert_embeddings(rows)
                    report = _replace(report, embedded=len(rows))
                except StorageError as e:
                    if "dim mismatch" in str(e):
                        logger.warning(
                            "skipping chunk-vec write: %s. Asset-vec retrieval "
                            "still active; chunk-text retrieval falls back to "
                            "BM25 only. Run `rm .dikw/dikw.sqlite && dikw "
                            "ingest` to reindex chunks under the new dim.",
                            e,
                        )
                    else:
                        raise
            elif embedder is not None:
                rows = await embed_chunks(
                    embedder,
                    to_embed,
                    model=cfg.provider.embedding_model,
                    batch_size=cfg.provider.embedding_batch_size,
                )
                await storage.upsert_embeddings(rows)
                report = _replace(report, embedded=len(rows))

        # Asset embeddings — only when multimodal is configured AND a real
        # mm provider is available. New-this-run assets only; previously
        # ingested asset binaries already have vectors from a prior run.
        if (
            multimodal_embedder is not None
            and mm_cfg is not None
            and mm_version_id is not None
            and new_assets_by_id
        ):
            asset_rows = await embed_assets(
                multimodal_embedder,
                list(new_assets_by_id.values()),
                project_root=root,
                model=mm_cfg.model,
                version_id=mm_version_id,
                batch_size=mm_cfg.batch,
            )
            if asset_rows:
                await storage.upsert_asset_embeddings(asset_rows)
            report = _replace(
                report,
                assets=len(new_assets_by_id),
                asset_embedded=len(asset_rows),
            )
        elif new_assets_by_id:
            # Materialized assets even without an mm embedder so the chunk
            # references resolve at query/render time.
            report = _replace(report, assets=len(new_assets_by_id))

        return report
    finally:
        if owned_mm is not None and hasattr(owned_mm, "aclose"):
            await owned_mm.aclose()
        await storage.close()


def _to_document(parsed: ParsedDocument, *, doc_id: str) -> DocumentRecord:
    return DocumentRecord(
        doc_id=doc_id,
        path=parsed.path,
        title=parsed.title,
        hash=parsed.hash,
        mtime=parsed.mtime,
        layer=Layer.SOURCE,
        active=True,
    )


def _replace(r: IngestReport, **kwargs: int) -> IngestReport:
    return IngestReport(
        scanned=kwargs.get("scanned", r.scanned),
        added=kwargs.get("added", r.added),
        updated=kwargs.get("updated", r.updated),
        unchanged=kwargs.get("unchanged", r.unchanged),
        chunks=kwargs.get("chunks", r.chunks),
        embedded=kwargs.get("embedded", r.embedded),
        assets=kwargs.get("assets", r.assets),
        asset_embedded=kwargs.get("asset_embedded", r.asset_embedded),
    )


# ---- Phase 1: query ------------------------------------------------------


async def query(
    q: str,
    path: str | Path | None = None,
    *,
    limit: int = 5,
    llm: LLMProvider | None = None,
    embedder: EmbeddingProvider | None = None,
    multimodal_embedder: MultimodalEmbeddingProvider | None = None,
) -> QueryResult:
    """Hybrid-search the wiki, feed the top hits to an LLM, and return cited answer.

    When ``cfg.assets.multimodal`` is configured *and* a
    ``multimodal_embedder`` is supplied (or buildable from the same
    config), the searcher activates the asset-vector channel so visual
    references contribute to retrieval.
    """
    cfg, _root, storage = await _with_storage(path)
    owned_mm: MultimodalEmbeddingProvider | None = None
    try:
        _embedder = embedder
        _llm = llm
        if _embedder is None:
            _embedder = build_embedder(cfg.provider)
        if _llm is None:
            _llm = build_llm(cfg.provider)

        mm_search: MultimodalSearch | None = None
        mm_cfg = cfg.assets.multimodal
        if mm_cfg is not None:
            try:
                active = await storage.get_active_embed_version(
                    modality="multimodal"
                )
            except NotSupported as e:
                logger.warning(
                    "storage backend doesn't support multimodal versioning "
                    "(%s); querying with text-only retrieval",
                    e,
                )
                active = None
            if active is not None and active.version_id is not None:
                mm_embedder = multimodal_embedder
                if mm_embedder is None:
                    mm_embedder = build_multimodal_embedder(
                        mm_cfg.provider,
                        base_url=mm_cfg.base_url,
                        batch=mm_cfg.batch,
                    )
                    owned_mm = mm_embedder  # close it ourselves below
                # Use the model recorded on the active version, not the
                # current cfg model — if the user just edited dikw.yml to
                # point at a new model but hasn't re-ingested yet, the
                # asset vectors in vec_assets_v<active> were produced by
                # the OLD model; querying with the new model would either
                # mismatch dim or rank against an incompatible space.
                mm_search = MultimodalSearch(
                    embedder=mm_embedder,
                    model=active.model,
                    asset_version_id=active.version_id,
                )

        searcher = HybridSearcher.from_config(
            storage,
            _embedder,
            cfg.retrieval,
            embedding_model=cfg.provider.embedding_model,
            multimodal=mm_search,
        )
        hits = await searcher.search(q, limit=limit)

        excerpts_block, citations = await _build_excerpts(storage, hits)
        if not citations:
            return QueryResult(
                answer="(no excerpts available — ingest sources first or rephrase)",
                citations=[],
            )

        approved = await storage.list_wisdom(status=WisdomStatus.APPROVED)
        applicable = pick_applicable(q, approved, limit=3)
        wisdom_block, applied_refs = _format_applicable_wisdom(applicable)

        prompt_tmpl = prompts.load("query")
        user_prompt = prompt_tmpl.format(
            question=q, wisdom=wisdom_block, excerpts=excerpts_block
        )
        response = await _llm.complete(
            system="You are the query-answering component of dikw-core.",
            user=user_prompt,
            model=cfg.provider.llm_model,
            max_tokens=cfg.provider.llm_max_tokens_query,
            temperature=0.2,
        )
        return QueryResult(
            answer=response.text.strip(),
            citations=citations,
            applied_wisdom=applied_refs,
        )
    finally:
        if owned_mm is not None and hasattr(owned_mm, "aclose"):
            await owned_mm.aclose()
        await storage.close()


def _format_applicable_wisdom(
    applicable: list[ApplicableWisdom],
) -> tuple[str, list[AppliedWisdomRef]]:
    if not applicable:
        return "_(none)_", []
    lines: list[str] = []
    refs: list[AppliedWisdomRef] = []
    for i, app in enumerate(applicable, start=1):
        tag = f"W{i}"
        summary = app.item.body.strip().splitlines()[0] if app.item.body.strip() else ""
        lines.append(
            f"[{tag}] ({app.item.kind.value}) {app.item.title}\n    {summary}".rstrip()
        )
        refs.append(
            AppliedWisdomRef(
                ref=tag,
                item_id=app.item.item_id,
                kind=app.item.kind.value,
                title=app.item.title,
            )
        )
    return "\n".join(lines), refs


# ---- Phase 2: synthesize + lint -----------------------------------------


async def synthesize(
    path: str | Path | None = None,
    *,
    force_all: bool = False,
    llm: LLMProvider | None = None,
    embedder: EmbeddingProvider | None = None,
) -> SynthReport:
    """Turn source docs into K-layer wiki pages via the configured LLM.

    By default only source docs that have never been synthesised are
    processed; pass ``force_all=True`` to re-synthesise every source.
    Embedding of new wiki pages is skipped when ``embedder`` is ``None``.
    """
    cfg, root, storage = await _with_storage(path)
    try:
        _llm = llm or build_llm(cfg.provider)

        sources = list(await storage.list_documents(layer=Layer.SOURCE, active=True))
        already: set[str] = set()
        if not force_all:
            for entry in await storage.list_wiki_log():
                if entry.action == "synth" and entry.src and entry.dst:
                    already.add(entry.src)

        report = SynthReport()
        tmpl = prompts.load("synthesize")
        persisted_any = False

        for src in sources:
            report = _sr_replace(report, candidates=report.candidates + 1)
            if src.path in already:
                report = _sr_replace(report, skipped=report.skipped + 1)
                continue

            body = _read_source_body(root, src)
            if body is None:
                report = _sr_replace(report, errors=report.errors + 1)
                await storage.append_wiki_log(
                    WikiLogEntry(
                        ts=time.time(),
                        action="synth",
                        src=src.path,
                        note="source body missing on disk",
                    )
                )
                continue

            user_prompt = tmpl.format(source_path=src.path, source_body=body)
            response = await _llm.complete(
                system="You synthesise K-layer wiki pages for dikw-core.",
                user=user_prompt,
                model=cfg.provider.llm_model,
                max_tokens=cfg.provider.llm_max_tokens_synth,
                temperature=0.3,
            )

            try:
                page = parse_synthesis_response(response.text, source_path=src.path)
            except SynthesisError as e:
                report = _sr_replace(report, errors=report.errors + 1)
                await storage.append_wiki_log(
                    WikiLogEntry(
                        ts=time.time(),
                        action="synth",
                        src=src.path,
                        note=f"parse error: {e}",
                    )
                )
                continue

            pre_existing = await storage.get_document(
                _doc_id_for(Layer.WIKI, page.path)
            )
            write_page(root, page)
            await _persist_wiki_page(
                storage=storage,
                root=root,
                page=page,
                embedder=embedder,
                embedding_model=cfg.provider.embedding_model,
            )
            await storage.append_wiki_log(
                WikiLogEntry(
                    ts=time.time(), action="synth", src=src.path, dst=page.path
                )
            )
            persisted_any = True
            if pre_existing is None:
                report = _sr_replace(report, created=report.created + 1)
            else:
                report = _sr_replace(report, updated=report.updated + 1)

        # Refresh the human-readable views after the batch so a partial run
        # still leaves the wiki internally consistent.
        if persisted_any or not (root / "wiki" / "index.md").exists():
            regenerate_index(root, updated=now_iso())
        entries = await storage.list_wiki_log()
        render_log(root, entries, updated=now_iso())

        return report
    finally:
        await storage.close()


async def lint(path: str | Path | None = None) -> LintReport:
    """Run the K-layer hygiene checker."""
    _cfg, root, storage = await _with_storage(path)
    try:
        return await run_lint(storage, root=root)
    finally:
        await storage.close()


def _read_source_body(root: Path, doc: DocumentRecord) -> str | None:
    abs_path = (root / doc.path).resolve()
    if not abs_path.is_file():
        return None
    # Route through the backend registry so HTML (and future) sources flow
    # through synth the same way markdown does.
    try:
        parsed = parse_any(abs_path, rel_path=doc.path)
    except (OSError, UnsupportedFormat):
        return None
    return parsed.body


async def _persist_wiki_page(
    *,
    storage: Storage,
    root: Path,
    page: WikiPage,
    embedder: EmbeddingProvider | None,
    embedding_model: str,
) -> None:
    """Index ``page`` into the K layer: document, chunks, embeddings, links."""
    doc_id = _doc_id_for(Layer.WIKI, page.path)
    body_hash = content_hash(page.body)
    abs_path = (root / page.path).resolve()
    mtime = abs_path.stat().st_mtime if abs_path.is_file() else time.time()

    await storage.put_content(body_hash, page.body)
    await storage.upsert_document(
        DocumentRecord(
            doc_id=doc_id,
            path=page.path,
            title=page.title,
            hash=body_hash,
            mtime=mtime,
            layer=Layer.WIKI,
            active=True,
        )
    )

    chunks = chunk_markdown(page.body)
    records = [
        ChunkRecord(doc_id=doc_id, seq=c.seq, start=c.start, end=c.end, text=c.text)
        for c in chunks
    ]
    chunk_ids = await storage.replace_chunks(doc_id, records)

    if embedder is not None and records:
        to_embed = [
            ChunkToEmbed(chunk_id=cid, text=r.text)
            for cid, r in zip(chunk_ids, records, strict=True)
        ]
        rows = await embed_chunks(embedder, to_embed, model=embedding_model)
        await storage.upsert_embeddings(rows)

    # Link graph — resolve against the current K-layer title index.
    k_docs = list(await storage.list_documents(layer=Layer.WIKI, active=True))
    title_to_path: dict[str, str] = {}
    for d in k_docs:
        if d.title and d.title not in title_to_path:
            title_to_path[d.title] = d.path
    parsed_links = parse_links(page.body)
    resolved, _unresolved = resolve_links(doc_id, parsed_links, title_to_path=title_to_path)
    for link in resolved:
        await storage.upsert_link(link)


def _sr_replace(r: SynthReport, **kw: int) -> SynthReport:
    return SynthReport(
        candidates=kw.get("candidates", r.candidates),
        created=kw.get("created", r.created),
        updated=kw.get("updated", r.updated),
        skipped=kw.get("skipped", r.skipped),
        errors=kw.get("errors", r.errors),
    )


# ---- Phase 3: distill + review ------------------------------------------


async def distill(
    path: str | Path | None = None,
    *,
    llm: LLMProvider | None = None,
    pages_per_call: int = 8,
) -> DistillReport:
    """Propose W-layer wisdom items from the current K-layer pages.

    ``pages_per_call`` caps how many K pages are fed to a single LLM call;
    each call produces zero or more ``<wisdom>`` blocks that are persisted
    as candidates when they satisfy the N≥2-evidence invariant.
    """
    cfg, root, storage = await _with_storage(path)
    try:
        _llm = llm or build_llm(cfg.provider)

        k_docs = list(await storage.list_documents(layer=Layer.WIKI, active=True))
        # Aggregate pages we can cite later — D and K together count as evidence sources
        source_docs = list(await storage.list_documents(layer=Layer.SOURCE, active=True))
        path_to_doc_id: dict[str, str] = {
            **{d.path: d.doc_id for d in k_docs},
            **{d.path: d.doc_id for d in source_docs},
        }

        report = DistillReport(pages_read=len(k_docs))
        if not k_docs:
            return report

        tmpl = prompts.load("distill")
        seen_ids: set[str] = {
            item.item_id
            for item in await storage.list_wisdom()
        }

        for batch in _chunked(k_docs, pages_per_call):
            pages_block = _render_pages_block(root, batch)
            user_prompt = tmpl.format(pages_block=pages_block)
            response = await _llm.complete(
                system="You distil W-layer wisdom items from a K-layer wiki.",
                user=user_prompt,
                model=cfg.provider.llm_model,
                max_tokens=cfg.provider.llm_max_tokens_distill,
                temperature=0.25,
            )
            parsed = parse_distill_response(response.text)
            report = _dr_replace(
                report,
                rejected=report.rejected + len(parsed.rejected),
            )
            for cand in parsed.candidates:
                if cand.item_id in seen_ids:
                    continue
                try:
                    await _persist_candidate(storage, root, cand, path_to_doc_id)
                except ValueError:
                    report = _dr_replace(report, errors=report.errors + 1)
                    continue
                seen_ids.add(cand.item_id)
                report = _dr_replace(report, candidates_added=report.candidates_added + 1)

        # Keep the append-only log up to date even if no candidates landed
        if report.candidates_added:
            await storage.append_wiki_log(
                WikiLogEntry(
                    ts=time.time(),
                    action="distill",
                    note=f"+{report.candidates_added} candidates",
                )
            )
            entries = await storage.list_wiki_log()
            render_log(root, entries, updated=now_iso())

        return report
    finally:
        await storage.close()


async def list_candidates(path: str | Path | None = None) -> list[WisdomItem]:
    _cfg, _root, storage = await _with_storage(path)
    try:
        return await storage.list_wisdom(status=WisdomStatus.CANDIDATE)
    finally:
        await storage.close()


async def approve_wisdom(
    item_id: str, path: str | Path | None = None
) -> ReviewResult:
    _cfg, root, storage = await _with_storage(path)
    try:
        return await _approve_item(storage, root=root, item_id=item_id)
    finally:
        await storage.close()


async def reject_wisdom(
    item_id: str, path: str | Path | None = None
) -> ReviewResult:
    _cfg, root, storage = await _with_storage(path)
    try:
        return await _reject_item(storage, root=root, item_id=item_id)
    finally:
        await storage.close()


async def _persist_candidate(
    storage: Storage,
    root: Path,
    candidate: WisdomCandidate,
    path_to_doc_id: dict[str, str],
) -> None:
    """Resolve candidate evidence against real doc_ids and persist everything."""
    resolved: list[WisdomEvidence] = []
    for ev in candidate.evidence:
        doc_id = path_to_doc_id.get(ev.doc_id)
        if doc_id is None:
            continue  # evidence pointing at an unknown doc — silently drop it
        resolved.append(
            WisdomEvidence(doc_id=doc_id, excerpt=ev.excerpt, line=ev.line)
        )
    if len(resolved) < 2:
        raise ValueError("candidate lost evidence after resolution")

    created_iso = now_iso()
    item = WisdomItem(
        item_id=candidate.item_id,
        kind=candidate.kind,
        status=WisdomStatus.CANDIDATE,
        path=None,
        title=candidate.title,
        body=candidate.body,
        confidence=candidate.confidence,
        created_ts=time.time(),
        approved_ts=None,
    )
    await storage.put_wisdom(item, resolved)
    write_candidate_file(root, candidate, created_iso=created_iso)


def _render_pages_block(root: Path, docs: list[DocumentRecord]) -> str:
    """Render a human-readable markdown dump of K pages for the distill prompt."""
    parts: list[str] = []
    for doc in docs:
        abs_path = (root / doc.path).resolve()
        if not abs_path.is_file():
            continue
        try:
            text = abs_path.read_text(encoding="utf-8")
        except OSError:
            continue
        # strip front-matter to keep the prompt compact
        if text.startswith("---\n"):
            _, _, rest = text.partition("\n---\n")
            text = rest.lstrip("\n")
        parts.append(f"### PAGE: {doc.path}\n\n{text.strip()}\n")
    return "\n---\n\n".join(parts)


def _chunked(seq: list[DocumentRecord], n: int) -> list[list[DocumentRecord]]:
    if n <= 0:
        return [seq]
    return [seq[i : i + n] for i in range(0, len(seq), n)]


def _dr_replace(r: DistillReport, **kw: int) -> DistillReport:
    return DistillReport(
        pages_read=kw.get("pages_read", r.pages_read),
        candidates_added=kw.get("candidates_added", r.candidates_added),
        rejected=kw.get("rejected", r.rejected),
        errors=kw.get("errors", r.errors),
    )


async def _build_excerpts(
    storage: Storage, hits: list[Hit]
) -> tuple[str, list[Citation]]:
    # Chunk-level fusion repeats doc_ids across hits, so a per-hit
    # ``get_document`` would issue O(hits) round trips for O(unique docs)
    # of useful work. Batch once up front.
    unique_doc_ids = list({h.doc_id for h in hits})
    docs_by_id = {
        d.doc_id: d for d in await storage.get_documents(unique_doc_ids)
    }

    citations: list[Citation] = []
    lines: list[str] = []
    for i, hit in enumerate(hits, start=1):
        doc = docs_by_id.get(hit.doc_id)
        if doc is None:
            continue
        excerpt = hit.snippet
        if not excerpt:
            chunk = await storage.get_chunk(hit.chunk_id)
            if chunk is not None:
                excerpt = chunk.text[:400]
        excerpt = (excerpt or "").strip()
        if not excerpt:
            continue
        citations.append(
            Citation(
                n=i,
                path=doc.path,
                title=doc.title,
                layer=doc.layer.value,
                seq=hit.seq,
                excerpt=excerpt,
            )
        )
        lines.append(
            f"[#{i}] ({doc.layer.value}) {doc.path}\n> {excerpt}"
        )
    return "\n\n".join(lines), citations
